name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      component:
        description: "Terraform component to plan"
        required: true
        type: choice
        options:
          - account
          - network
          - vcf_etl
      environment:
        description: "Environment to plan"
        required: true
        default: "dev"
        type: choice
        options:
          - dev

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    env:
      COMPONENT: ${{ github.event.inputs.component }}
      AWS_GLOBAL_LEVEL_ID: ${{ vars.AWS_GLOBAL_LEVEL_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gms-dev-account-github-actions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run setup script
        run: bash .github/workflows/scripts/tf-runner-prep.sh
      - name: Terraform Plan
        working-directory: infrastructure
        env:
          TF_ACTION: plan
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          COMPONENT: ${{ github.event.inputs.component }}
          PROJECT: ${{ vars.PROJECT }}
        run: bash ../.github/workflows/scripts/tf-run.sh
      - name: Upload VCF files to raw variants bucket
        run: |
            aws s3 sync test-data/vcf \
              s3://gms-raw-variants/vcf